Add notice for potential need to increase Github licenses
gruntwork-io/docs pull request #1728
Opened 2024-05-17 15:25 UTC by oredavids

2024-05-17 15:36 UTC, yhakbar approved these changes

2024-05-17 15:38 UTC, yhakbar commented on _docs-sources/pipelines/security/machine-users.mdx
> +We recommend creating two machine users for this use case, but you can adjust based on your organization's needs. Ensure the correct tokens are created and the permissions for the machine users and t
```suggestion
We recommend creating two machine users for this use case, but you can adjust this based on your organization's needs. Ensure that the correct tokens are created and the permissions for the machine users and tokens are appropriate for their required access.
```

2024-05-17 15:39 UTC, yhakbar requested changes
Grammar updates.

2024-05-17 15:42 UTC, oredavids commented
> Grammar updates.

@yhakbar done.

2024-05-17 15:51 UTC, yhakbar approved these changes

2024-05-21 20:05 UTC, ZachGoldberg approved these changes

2024-05-21 20:14 UTC, merged