feat: pipelines config doc page
gruntwork-io/docs pull request #1806
Opened 2024-06-28 00:22 UTC by ZachGoldberg

![image](https://github.com/gruntwork-io/docs/assets/148103/a57248e6-dba7-4588-afc4-14bb95f2b4f0)
![image](https://github.com/gruntwork-io/docs/assets/148103/aac9f376-82ab-4388-97e4-459cf4527a28)

2024-06-28 12:03 UTC, yhakbar requested changes

2024-06-28 12:03 UTC, yhakbar commented on _docs-sources/pipelines/overview/configuration.md
> +  # Only set to true for delegated (vended) accounts from account factory
```suggestion
  # Only set to true for delegated (vended) repositories from account factory
```

2024-06-28 12:03 UTC, yhakbar commented on _docs-sources/pipelines/overview/configuration.md
> +  # Only set to true for infra-live-access-control
```suggestion
  # Only set to true for infrastructure-live-access-control
```

2024-06-28 12:03 UTC, yhakbar commented on _docs-sources/pipelines/overview/configuration.md
> +    # - account-identifiers: List of account identifiers that will be created (required).
I think it's confusing to have what looks like valid YAML list elements under `sdlc` in this comment. Consider placing each comment right above the relevant configuration.

2024-07-01 23:23 UTC, ZachGoldberg commented
@yhakbar mind re-reviewing?

2024-07-02 17:07 UTC, merged