WIP PR from Edify
gruntwork-io/docs pull request #2237
Opened 2024-12-06 22:39 UTC by ZachGoldberg

2024-12-11 19:54 UTC, yhakbar commented on docs/2.0/docs/accountfactory/architecture/index.md
> +In your `infrastructure-live-root` account, the `_new-account-requests` directory acts as an input for the Gruntwork Control Tower Module. This module runs within your management account and uses AWS
```suggestion
In your `infrastructure-live-root` repository, the `_new-account-requests` directory acts as an input for the Gruntwork Control Tower Module. This module runs within your management account and uses AWS Control Tower to provision new accounts.
```

2024-12-12 00:14 UTC, ZachGoldberg commented on docs/2.0/docs/accountfactory/architecture/logging.md
> +Gruntwork Account Factory automatically configures AWS CloudTrail to log all operations in your AWS accounts. By default, CloudTrail maintains your data for 90 days and is queryable using CloudTrail
```suggestion
Gruntwork Account Factory automatically configures AWS CloudTrail to log all operations in your AWS accounts. By default, CloudTrail maintains your data for 90 days and is queryable using the AWS Console CloudTrail UI.
```

2024-12-12 00:16 UTC, ZachGoldberg commented on docs/2.0/docs/accountfactory/architecture/logging.md
> +Granting access to the audit logs requires security configurations in the originating account (e.g., the account in which the events are occurring) and the `logs` account. The originating account con
```suggestion
Granting access to the audit logs requires security configurations in the originating account (e.g., the account in which the events are occurring) and the `logs` account. The originating account contains the CloudTrail trail itself, which should only be viewable by account administrators. The `logs` account contains the AWS S3 bucket that contains synchronized CloudTrail logs from all logs.
```

2024-12-12 00:18 UTC, ZachGoldberg commented on docs/2.0/docs/library/architecture/opentofu-terraform-compatibility.md
> +Version 1.5.7 is the final release of HashiCorp Terraform, licensed under the MPLv2 open-source license. Versions up to and including v1.5.7 remain MPLv2 licensed and continue to function.
```suggestion
Version 1.5.7 is the final release of HashiCorp Terraform, licensed under the MPLv2 open-source license. Versions up to and including v1.5.7 remain MPLv2 licensed and thus can continue to be used with Gruntwork.
```

2024-12-12 00:19 UTC, ZachGoldberg commented on docs/2.0/docs/library/architecture/opentofu-terraform-compatibility.md
> +Gruntwork advises all customers to adopt [OpenTofu](https://opentofu.org/) as a "drop-in" replacement for HashiCorp Terraform. We will prioritize development of OpenTofu releases, test for compatibil
```suggestion
Gruntwork advises all customers to adopt [OpenTofu](https://opentofu.org/) as a "drop-in" replacement for HashiCorp Terraform. We will prioritize development with OpenTofu releases, test for compatibility, and provide full support for any issues related to our modules and OpenTofu.
```

2024-12-12 00:22 UTC, ZachGoldberg commented on docs/2.0/docs/library/architecture/overview.md
> +1. `modules`: This folder contains the core implementation code. All modules you use and deploy are defined here. For example, you can locate the ECS cluster module in the `terraform-aws-ecs` reposit
```suggestion
1. `modules`: This folder contains the core implementation code. All modules you use and deploy are defined here. For example, you can locate the ECS cluster module in the `terraform-aws-ecs` repository within the `modules/ecs-cluster` folder.
```

2024-12-12 00:29 UTC, ZachGoldberg commented on docs/2.0/docs/library/concepts/modules.md
> +Consider [Service Modules](/2.0/docs/library/concepts/service-modules) for greater convenience.
```suggestion
Consider [Service Modules](/2.0/docs/library/concepts/service-modules) when optimizing for greater convenience.
```

2024-12-12 00:30 UTC, ZachGoldberg commented on docs/2.0/docs/library/concepts/modules.md
> +Each use case includes one or more Subject Matter Expert (SME) topics, such as AWS account management, VPC/Networking, EKS, ECS, and RDS. While SME topics are a first-class concept within Gruntwork,
```suggestion
```

2024-12-12 00:34 UTC, ZachGoldberg reviewed
Made a handful of small tweaks, otherwise looks good to me!

2024-12-16 19:52 UTC, yhakbar requested changes
These are the issues I was able to spot.

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/architecture/overview.md
> +1. `examples`: This folder includes sample code demonstrating how to use the modules in the `modules` folder. These examples allow you to try the modules without writing code. Navigate to one of the
```suggestion
1. `examples`: This folder includes sample code demonstrating how to use the modules in the `modules` folder. These examples allow you to try the modules without writing code. Navigate to one of the example directories, follow the steps in the README (e.g., run `tofu apply`), and you will have a working module. These examples serve as executable documentation.
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/architecture/overview.md
> +1. `examples`: This folder provides sample code demonstrating how to use the services in the `modules` folder. These examples enable you to deploy services without writing code. Navigate to a directo
```suggestion
1. `examples`: This folder provides sample code demonstrating how to use the services in the `modules` folder. These examples enable you to deploy services without writing code. Navigate to a directory, follow the README instructions (e.g., run `tofu apply`), and you'll have working infrastructure. This folder contains two sub-folders:
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/architecture/overview.md
> +1. `for-production`: These examples are optimized for direct production use. They showcase how Gruntwork's Reference Architecture integrates a complete tech stack using the Gruntwork Service Catalog.
```suggestion
1. `for-production`: These examples are optimized for direct production use. They showcase how Gruntwork's Reference Architecture integrates a complete tech stack using the Gruntwork Service Catalog. To keep the code DRY and manage dependencies, you can deploy these examples using [Terragrunt](https://terragrunt.gruntwork.io/). Terragrunt is not required to use the Gruntwork Service Catalog; you can use OpenTofu, Terraform or Terraform Cloud/Enterprise, as described [here](https://docs.gruntwork.io/reference/services/intro/deploy-new-infrastructure#how-to-deploy-terraform-code-from-the-service-catalog).
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/architecture/overview.md
> +1. [Terratest](https://terratest.gruntwork.io/). All modules are functionally validated with automated tests written in Terratest.
```suggestion
1. [Terratest](https://terratest.gruntwork.io/). All modules are functionally validated with automated tests written using Terratest.
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/architecture/overview.md
> +1. [Packer](https://www.packer.io/). The Library includes definitions for _machine images_ (e.g., VM images) using Packer. A common use case is creating Amazon Machine Images (AMIs) for EC2 instances
```suggestion
1. [Packer](https://www.packer.io/). The Library includes definitions for _machine images_ (e.g., VM images) using Packer. A common use case is creating Amazon Machine Images (AMIs) for EC2 instances, where configuration is defined entirely in code. After building an AMI, you can deploy it using OpenTofu/Terraform.
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/architecture/overview.md
> +1. [Terraform](https://www.terraform.io/). The Library contains nearly 300 Terraform modules covering common AWS use cases. All modules are compatible with vanilla [Terraform](https://www.terraform.i
```suggestion
1. [OpenTofu](https://opentofu.org/)/[Terraform](https://www.terraform.io/). The Library contains nearly 300 OpenTofu/Terraform modules covering common AWS use cases. All modules are compatible with [OpenTofu](https://opentofu.org/), [Terraform](https://www.terraform.io/), [Terragrunt](https://terragrunt.gruntwork.io/), or third-party pipeline tools like [Terraform Cloud](https://www.hashicorp.com/blog/announcing-terraform-cloud/) and [Terraform Enterprise](https://www.terraform.io/docs/enterprise/index.html).
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/concepts/module-defaults.md
> +Module defaults allow infrastructure as code developers to reference a terraform module, set locals, and set default (but mutable) variable values. This pattern helps keep Terragrunt architecture DRY
```suggestion
Module defaults allow infrastructure as code developers to reference an OpenTofu/Terraform module, set locals, and set default (but mutable) variable values. This pattern helps keep Terragrunt architecture DRY, reducing the likelihood of errors when making changes across environments.
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/concepts/modules.md
> +Most modules are written in Terraform and define multiple AWS resources.
```suggestion
Most modules are written in OpenTofu/Terraform and define multiple AWS resources.
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/concepts/modules.md
> +Consider the [rds module](/reference/modules/terraform-aws-data-storage/rds). This Terraform module creates an RDS database, the IAM roles required to operate it, optional read replicas, database sub
```suggestion
Consider the [`rds` module](/reference/modules/terraform-aws-data-storage/rds). This OpenTofu/Terraform module creates an RDS database, the IAM roles required to operate it, optional read replicas, database subnet groups, and relevant security groups.
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/concepts/modules.md
> +To browse the module catalog, see the [Library Reference](/library/reference) or visit the [private Gruntwork GitHub repos](https://github.com/orgs/gruntwork-io/repositories?q=&type=private&language=
```suggestion
To browse the module catalog, see the [Library Reference](/library/reference) or peruse the [private Gruntwork GitHub repositories using your subscription](https://github.com/orgs/gruntwork-io/repositories?q=&type=private&language=&sort=).
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/concepts/modules.md
> +Gruntwork employs AWS and Terraform experts who monitor updates from AWS, Terraform, and the broader DevOps community. Feedback from the Gruntwork customer community also informs updates. They incorp
```suggestion
Gruntwork employs AWS and OpenTofu/Terraform experts who monitor updates from AWS, OpenTofu, Terraform, and the broader DevOps community. Feedback from the Gruntwork customer community also informs updates. They incorporate the most significant updates into new features and releases.
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/concepts/overview.md
> +The Library promotes code reusability, modularity, and consistency. It encapsulates years of experience building AWS infrastructure into pre-built modules you can integrate into your environment.
```suggestion
The Library promotes code reusability, modularity, and consistency. It encapsulates years of experience building AWS infrastructure into pre-built modules you can integrate into your infrastructure management.
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/concepts/overview.md
> +"Building block" modules, referred to as **modules**, are authored by Gruntwork and written in OpenTofu configuration files. They capture best-practice patterns for specific infrastructure components
```suggestion
"Building block" modules, referred to as **modules**, are authored by Gruntwork and written in OpenTofu/Terraform configuration files. They capture best-practice patterns for specific infrastructure components and are limited in scope yet highly reusable. For example, the `vpc-flow-logs` module adds VPC Flow Logs functionality to an existing VPC but does not create a VPC.
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/concepts/principles/be-judicious-with-new-features.md
> +New OpenTofu features can streamline module authoring but may also require consumers to adopt newer OpenTofu versions. This requirement can pose challenges for organizations that cannot upgrade promp
```suggestion
New OpenTofu features can streamline module authoring and provide more features, but may also require that consumers adopt newer OpenTofu versions. This requirement can pose challenges for organizations that cannot upgrade OpenTofu versions promptly, but want to keep using the latest version of our modules.
```

2024-12-16 19:52 UTC, yhakbar commented on docs/2.0/docs/library/concepts/principles/be-judicious-with-new-features.md
> +Modules in the Library often depend on each other. All dependent modules must be updated if a module update requires a newer OpenTofu version.
```suggestion
Modules in the Library often depend on each other. All dependent modules must be updated to require a newer OpenTofu version if a dependent module update requires a newer OpenTofu version.
```

2024-12-16 20:13 UTC, merged